CREATE TABLE Students(ID Number, Prog_ID NUMBER, Name VARCHAR2(50), Phone VARCHAR2(15), Email VARCHAR2(50), Address VARCHAR2(50), Dom_OR_Int VARCHAR2(13), Enroll_Notes VARCHAR2(200), Admin_Status VARCHAR2(20));
ALTER TABLE Students ADD CONSTRAINT Students_PK PRIMARY KEY(ID);
ALTER TABLE Students ADD CONSTRAINT Students_FK FOREIGN KEY(Prog_ID) REFERENCES Programs(ID);
ALTER TABLE Students ADD CHECK(Dom_OR_Int IN (‘Domestic’, ‘International’));

CREATE TABLE Requirements(ID Number, Prog_ID NUMBER, Section VARCHAR2(50), Field_Name VARCHAR2(50));
ALTER TABLE Requirements ADD CONSTRAINT Requirements_PK PRIMARY KEY(ID);
ALTER TABLE Requirements ADD CONSTRAINT Requirements_FK FOREIGN KEY(Prog_ID) REFERENCES Programs(ID);

CREATE TABLE StudentTracking(Req_ID NUMBER, Stu_ID NUMBER, ANS VARCHAR2(50));
ALTER TABLE StudentTracking ADD CONSTRAINT StudentTracking_FK1 FOREIGN KEY(Stu_ID) REFERENCES Students(ID);
ALTER TABLE StudentTracking ADD CONSTRAINT StudentTracking_FK2 FOREIGN KEY(Req_ID) REFERENCES Requirements(ID);

CREATE TABLE Employees(ID NUMBER, Username VARCHAR2(50), Phone VARCHAR2(15), Email VARCHAR2(50), Department VARCHAR(50), Password VARCHAR2(50));
ALTER TABLE Employees ADD CONSTRAINT Employees_PK PRIMARY KEY(ID);

CREATE TABLE Fees(ID NUMBER, Prog_ID NUMBER, Fee_Name VARCHAR2(50), Dom_Price NUMBER, Int_Price NUMBER);
ALTER TABLE Fees ADD CONSTRAINT Fees_PK PRIMARY KEY(ID);
ALTER TABLE Fees ADD CONSTRAINT Requirements_FK FOREIGN KEY(Prog_ID) REFERENCES Programs(ID);

CREATE TABLE Programs(ID NUMBER, Prog_Name VARCHAR2(50));
ALTER TABLE Programs ADD CONSTRAINT Programs_PK PRIMARY KEY(ID);
