<?php
include "v_tech_nav.php";
?>
<div id="main-container">

    <div class="content" id="item1">
        <p>this is new content form rafael
        </p>

    <div class="content" id="ResetPass">
        <h1> Reset Password </h1>
        <p> 1. Click on the 'Forgot your password?' link on the login page </p>
        <img src="images/ResetPass1.jpg" alt="Reset Password Step 1">

        <p> 2. Enter your username and click submit </p>

        <p> 3. Admin will review your request for a password reset and send an email containing your new password within 2 business days </p>

    </div>

    <div class="content" id="GenerateInvoice">
        <h1> Generate Invoice </h1>
        <p> 1. Navigate to the 'Generate Invoice' page under the 'Export Documents' tab in the navigation bar </p>
        <img src="images/GenerateInvoice1.jpg" alt="Generate Invoice Step 1">

        <p> 2. Fill out the appropriate information for the invoice </p>
        <!-- Put information about the form here -->
        <img src="images/GenerateInvoice2.jpg" alt="Generate Invoice Step 2">
        <ul>
            <li> <strong> Invoice Number: </strong> An autogenerated number is generated </li>
            <li> <strong> Bill To: </strong> Full name of the recipient </li>
            <li> <strong> Program: </strong> The program the recipient has enrolled in </li>
            <li> <strong> Note: </strong> Any additional notes that may need to be added </li>
            <li> <strong> Quantity: </strong> Quanity of the fee </li>
            <li> <strong> Description: </strong> Description of the fee </li>
            <li> <strong> Unit Price: </strong> Unit price of the fee </li>       
            <li> <strong> Total: </strong> Calculates the total amount of the fee. Autogenerated after 'Quantity' and 'Unit Price' fields are filled </li>     
            <li> <strong> Send to this student: </strong> When checkbox is enabled, an input field will appear for you to enter the recipients email in. The invoice will be sent to them after the 'generate' button is clicked </li>
            <li> <strong> Subtotal: </strong> Autogenerated when invoice is created </li>
            <li> <strong> Total Fees: </strong> Autogenerated when invoice is created </li>
        </ul>

        <p> 3. Click the 'Preview' or 'Generate' button to generate invoice
            <!-- Put information about the preview and generate button here -->
            <ul>
                <li> <strong> Preview: </strong> Generates a pdf preview of the invoice in a new tab </li>
                <li> <strong> Generate: </strong> Generates and downloads a pdf copy of the invoice </li>
            </ul>
        </p>      
    </div>



</div>

    <?php
    include "v_tech_footer.php";
    ?>
</div><!--end of wrapper-->



