<?php
$labels = [
    "Student ID"
    "Photo ID"
    "Application Form"
    "Application Fee with Paid Invoice"
    "Application Essay"
    "Character Reference Letter"
    "Resume"
    "Intro of Massage Course Day One from"
    "Intro of Massage Course Day One to"
    "Intro of Message fee with paid invoice"
    "Intro of message Course Complete"
    "Welcome Letter Sent"
    "English test result (for non-english speaker)"
    "English Language Competency"
    "High School Diploma & Transcipt (Or above)"
    "CRC result"
    "Medical notes from Physican"
    "Interview Date and Time"
    "Interview Approved"
    "Student Email"
    "Letter of Acceptance Issued Date"
    "Enrollment Contract"
    "Student & program handbooks"
    "Ackmowledgement & Agreement Form Received Date:"
    "Photography Waiver Form Receive Date:"
    "Self-Declaration of Health Notice Receive Date:"
    "Payment Options"
    "Student ID Card Issued"
    "RMT Student Learning Materials"
];
